export const productActionType = {
  FETCHING_START: 'FETCHING_START',
  FETCHING_SUCCESS: 'FETCHING_SUCCESS',
  FETCHING_ERROR: 'FETCHING_ERROR',
  ADD_TO_CART: 'ADD_TO_CART',
  WISH_LIST: 'WISH_LIST',
  REMOVE_WISH_LIST: 'REMOVE_WISH_LIST'
}
